---
- name: Creat folder in Ubuntu
  ansible.builtin.file:
    path: "{{ dst_ubuntu }}"
    state: absent
  when: ansible_os_family == "Debian"

- name: Creat folder in Ubuntu
  ansible.builtin.file:
    path: "{{ dst_centos }}"
    state: absent
  when: ansible_os_family == "RedHat"

