---
# tasks file for delpoy_apache_web
- block:        #========Bloch for RedHat========

  - name: Install apache in RedHat
    yum: name=httpd state=latest
    notify: Open 80 port in RedHat

  - name: Start Webservice and enable autostart in RedHat
    service: name=httpd state=started enabled=yes

  when: ansible_os_family == "RedHat"

- block:        #========Bloch for Debian========

  - name: Install apache in Debian
    yum: name=apache2 state=latest
    notify: Open 80 port in Debian

  - name: Start Webservice and enable autostart in Debian
    service: name=apache2 state=started enabled=yes

  when: ansible_os_family == "Debian"

- name: Generate and copy Index.html
  template: src=index.j2 dest={{ dst_file }}/index.html
  notify:
      - Restart Apach for RedHat
      - Restart Apach for Debian

